repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
        args: [-b, main, -b, develop]
      - id: detect-private-key
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
        exclude: alembic

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--config=.flake8, src/, tests/]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        exclude: alembic
        additional_dependencies: [types-bleach==6.1.0.20240331]

  - repo: local
    hooks:
        - id: pytest
          name: pytest
          description: 'Run tests with pytest'
          entry: 'poetry run pytest -vv'
          language: python
          types: [ python ]
          require_serial: true
          pass_filenames: false
          always_run: true
